var spacer = 130;
var radiusMultiplier = 18;
var radiusAdder = 4;
var nucleotides = "ACGT";

var maxRadius = ((nucleotides.length - 1) + radiusAdder) * radiusMultiplier;

// BOOM!
window.onload = function() {
	makeSelectTag();
	document.getElementById("kakapo").click();
};

// Turns a nucleotide into a number
var nucleotideToNum = function(char) {
	return nucleotides.indexOf(char);
}

// Writes visualization to div#birdVis
// param data: array of raw numbers used for computing radii
// param colors: array of colors to be applied to shapes
var writeVis = function(data, colors){
	document.getElementById("birdVis").innerHTML = "";
	var birdVis = Raphael("birdVis");

	var currX = 0;
	var currY = 0;
	for (var i = 0; i < data.length; i++) {
		var radius = (data[i] + radiusAdder) * radiusMultiplier;
		var newCircle = birdVis.circle(currX, currY, radius);
		newCircle.attr({fill: colors[data[i]], stroke: colors[data[i]]});
		currX += radius + spacer;
		if (currX > screen.width) {
			currX = 0;
			currY += maxRadius + spacer;
		}
	}
};

// Makes a tags for the page
// Binds clicks to graph updates
var makeSelectTag = function() {
	for (var bird in birds) {
		var btn = document.createElement("a");
		btn.textContent = birds[bird].name;
		btn.id = bird;
		btn.className = "button chooser";
		document.getElementById("choicesContainer").appendChild(btn);
		btn.onclick = function(e) {
			e.preventDefault();
			var allButtons = document.getElementsByClassName("chooser");
			for (var i = 0; i < allButtons.length; i++) {
				allButtons[i].className = "button chooser";
			}
			this.className = "button chooser active";
			changeBird(this.id);
		};
	}
};

// Changes the graph to show the selected bird
// Param newBird: the simple string representing the type of bird
var changeBird = function(newBird) {
	writeVis(makeData(birds[newBird].seq), birds[newBird].colors);
};

// Takes a DNA char string
// Returns an array of nums
var makeData = function(str) {
	return str.split('').map(function(char) { return nucleotideToNum(char); });
}

// Bird data!
var birds = {
	kakapo: {
		name: "Kakapo",
		seq: "CCCCTATTGCAAAACTCATCCTAACCCTAAGCCTCCTCCTAGGAACAACAATTACAATCTCAAGCAACCACTGAATAATAGCTTGAACCGGATTAGAAATTAATACTCTAGCTATTATCCCCCTAATCTCAAAATCCCATCACCCTCGAGCCATTGAAGCGGCAATCAAATACTTCCTAGTACAAGCAACAGCTTCAGCACTAATTCTCTTCTCTAGCATAACTAATGCATGATTCACCGGACAATGAGATATTACTCAACTCACCAACCCCCCATCATGCCTTCTTCTAACTACCGCAATTGCTATCAAACTAGGACTAACACCTTTCCACTTCTGATTTCCAGAAGTACTTCAAGGTTCATCCCTTATCACAGCCATGCTACTATCAACAATAATAAAACTTCCACCCACTACTATCCTATTCCTTACATCACATTCACTCAACCCCACCCTACTTACCATTATAGCTATTACATCAGTCGCTCTAGGTGGCTGAATAGGACTTAATCAAACACAAACCCGAAAAGTCCTAGCCTTCTCATCAATCTCCCATCTAGGCTGAATAACCATTATCATTATCTACAATCCAAAACTCACCTTACTAGCCTTCTACCTCTATATCTTGATTACCAGCTCCATCTTCCTCACTATAAACACAACCAAAACACTAAAACTACCAACACTATTAACCTCATGGACCAAAGCACCTATATTAAACACAACCCTCATGCTAACTCTACTATCACTAGCAGGCCTCCCTCCACTAACAGGTTTCCTACCAAAATGACTTATCATTCAAGAGCTCATTAAACAAGAAATAACTACAACAGCTATAATCATCTCCATACTATCACTCCTAGGGCTTTTTTTCTACCTACGCCTACCATACTGTTCAACAATCACACTCCCTCCCAACCCCTCAAACAAAATAAAACAATGATTGACTAAAAAACCAACCAACACTCCAATCTCTATTCTTACCTCCCTATCCATCTCACTTCTTCCACTCTCCCCTATAATCCTTACCATTACTTAAGAAACTTAGGATAATCTAAACCAAAG",
		colors: ["red", "purple", "silver", "pink"]
	},
	pionus: {
		name: "Maximilian Pionus",
		seq: "ATAACTCCCATTGCAAAACTAATCTCAGCCCTAAGTATCCTGCTAGGAACAACAATAACAATCACAAGTAACCACTGAGCCATAGCTTGGGCAGGACTAGAAATCAACACCCTATCAATCATCCCCATAATCTCAAAATCCCACCACCCACGAGCCGTTGAAGCAGCAACCAAGTACTTCCTAGTACAAGCTGCCGCTTCAACACTAGTACTCTTCTCAAGCACAATCAACGCATGACACACAGGACAATGAGACATCACCCTACTCACCCATCCCCCAGCATGTCTCCTACTAACCACCGCAGTTGCTATTAAGCTGGGCCTAACTCCATTCCACTTTTGATTTCCAGAAGTACTCCAAGGGTCATCCCTCCCCACAGCCCTACTTCTCTCAACAGTAATAAAACTCCCACCAATTACACTCCTACTAATCACATCCCACTCACTAAACCCTGTCCTACTCACTACCATATCCATTATATCCGTCGCCCTTGGCGGCTGAATGGGACTAAACCAAACACAAACCCGAAAAATTATAGCCTTCTCATCCATCTCCCACCTGGGCTGAATAACATCCATTATCACCTACAGCCCAAAACTAACCCTACTAACCTTCTACGCCTACGCCCTAATAACAACCTCCATCTTCCTCACTATAAACACAACCAACACCTTAAAACTATCAACACTAATGACTGCATGAACCAAAACTCCCATACTAAACACAACCCTCATACTAACACTACTATCACTAGCAGGCCTCCCCCCACTAACAGGCTTCCTGCCCAAATGACTCATCATCCAAGAACTCGTCAAGCAAGAAATAACCACAACAGCCACAATCATCTCCATAATATCGCTCCTAGGGTTATTCTTCTACCTACGCCTAGCATACTGCTCCACTATCACACTCCCCCCCAACCCCTCTAGCAAGATAAAACAGTGATCCACTAAAAACCCAACCAACACTCTAGTCTCCACACTCACCTCCCTGTCCATCTCACTCCTCCCACTCTCCCCTATAATCCTCACCACCACTTAA",
		colors: ["olive", "green", "silver", "purple"]
	},
	barraband: {
		name: "Barraband",
		seq: "ATGAGTCCCCTTACAAAACTTATTCTAACTACAAGTCTGCTCACAGGGACAACAATCACAATCACAAGCAACCACTGACTAATAGCCTGAACCGGATTAGAAATCAACACCTTAGCCATCATCCCCCTAATCTCAAAATCCCACCACCCACGAGCCATCGAAGCAGCAACCAAATACTTCCTAGTACAAGCAGCAGCCTCCACACTAATACTCTTCTCAAGCACAATAAACGCATGATTTACTGGACAGTGAGACATCACCCAGCTCACCCACCCTCCATCATCCGCTCTACTAACCGCTGCAATCGCTATTAAACTAGGCCTAGCCCCATTCCACTTCTGATTTCCAGAAGCACTCCAAGGGTCATCCCTTACCACGGCCCTCCTTCTCTCAACAGTAATAAAACTCCCACCAACTACCATTCTCCTACTCACATCACACTCACTAAACCCAACACTACTCACCACCATATCCATCATATCCATCGCCCTAGGTGGATGAATAGGACTTAACCAAACACAAACCCGCAAAATCCTAGCCTTCTCCTCCATTTCACACCTAGGCTGAATAACCACCATCATCATCTACAACCCAAAACTAACCCTACTAACCTTCCTCACCTACATCCTAATAACAACCTCTATCTTTCTCACCATAAACACAACCAACACCCTAAAGCTACCAACGCTAATAACCTCCTGAACCAAAACCCCCACCCTAAGCACAACCCTCATACTAACCCTCCTCTCACTAGCGGGTCTCCCCCCACTAACAGGATTTTTACCCAAATGACTCATCATCCAAGAGCTCACTAAACAAGAAATAACCACAACAGCTACAATCATCTCTATATTCTCACTCCTAGGACTATTCTTCTACCTCCGCTTGGCATACTGTTCAACAATCACCCTACCTCCAAACCCCTCAAACAAAATAAAACAATGATCCCCTAAAAAACCAACAAACATCCTAATCTCTACATCTACCTCACTATCCACCTCACTCCTACCACTCTCCCCTATAATTCTCACCACCATTTAA",
		colors: ["red", "yellow", "peach", "green"]
	}
};